### ISSUE TITLE
nest scrypted

### ISSUE THREAD

**Issue by RuntyCascade** [koush/scrypted-nest#15]
recently installed Scrytped. searched for plugins in scrypted and installed Nest plugin. getting this error:
starting plugin @scrypted/nest 0.0.13
failure loadZip TypeError: Cannot read properties of null (reading 'getData')
    at Object.loadZip (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:442:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/src/rpc.ts:458:37)

**Comment by koush** [comment]
use google-device-access. nest is deprecated.
